#!/usr/bin/env python3
"""Bake vendored CSS/SVG animations into offline PNG frames for the mods sandbox.

Needs Python Pillow, Playwright, and Chromium. Runtime needs none of these.
Run from any directory: python scripts/bake-pets.py --chromium /usr/bin/chromium
"""
import argparse
import base64
import io
import json
import math
from pathlib import Path

from PIL import Image
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
SIZE, COLS, FRAMES = 80, 12, 32


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--chromium', default='/usr/bin/chromium')
    args = parser.parse_args()
    source = ROOT / 'assets/clawd-pets'
    catalog = json.loads((source / 'catalog.json').read_text())
    pets = catalog['pets']
    rows = math.ceil(len(pets) / COLS)
    # Separate documents isolate the upstream SVGs' repeated CSS names and IDs.
    documents = [(source / 'svg' / f"clawd-{p['id']}.svg").read_text() for p in pets]
    with sync_playwright() as play:
        browser = play.chromium.launch(executable_path=args.chromium, args=['--no-sandbox'])
        page = browser.new_page(viewport={'width': SIZE * COLS, 'height': SIZE * rows})
        page.route('**/*', lambda route: route.abort())
        page.set_content('<style>body{margin:0;display:grid;grid-template-columns:repeat(12,80px)}iframe{border:0;width:80px;height:80px}</style>')
        for svg in documents:
            page.evaluate('html => { const f=document.createElement("iframe"); f.srcdoc=html; document.body.append(f); }',
                          '<style>html,body{margin:0;width:80px;height:80px;overflow:hidden}svg{width:80px;height:80px}</style>' + svg)
        page.wait_for_function('Array.from(document.querySelectorAll("iframe")).every(f=>f.contentDocument?.querySelector("svg"))')
        loops = page.evaluate('''() => Array.from(document.querySelectorAll('iframe'), f => {
          const animations = f.contentDocument.getAnimations();
          let loop = 1000;
          const gcd = (a,b) => b ? gcd(b,a%b) : a;
          for (const a of animations) {
            a.pause();
            const timing = a.effect.getTiming();
            const d = Math.round(Number(timing.duration) * (timing.direction.includes('alternate') ? 2 : 1));
            if (d > 0) loop = loop / gcd(loop,d) * d;
          }
          // Complex, incommensurate loops are sampled over eight seconds.
          return Math.min(8000, Math.max(2000, loop));
        })''')
        frames = [[] for _ in pets]
        for index in range(FRAMES):
            page.evaluate('''({index,loops,count}) => Array.from(document.querySelectorAll('iframe')).forEach((f,i) => {
              for (const a of f.contentDocument.getAnimations()) a.currentTime = index * loops[i] / count;
            })''', {'index': index, 'loops': loops, 'count': FRAMES})
            image = Image.open(io.BytesIO(page.screenshot(omit_background=True))).convert('RGBA')
            for i in range(len(pets)):
                x, y = i % COLS * SIZE, i // COLS * SIZE
                frames[i].append(image.crop((x,y,x+SIZE,y+SIZE)))
            print(f'Captured {index + 1}/{FRAMES}', flush=True)
        browser.close()
    contact = Image.new('RGBA', (SIZE * COLS, SIZE * rows), '#241c19')
    for i, pet in enumerate(pets):
        boxes = [f.getbbox() for f in frames[i] if f.getbbox()]
        if not boxes:
            raise ValueError(f"Blank animation: {pet['id']}")
        box = (max(0,min(b[0] for b in boxes)-2), max(0,min(b[1] for b in boxes)-2),
               min(SIZE,max(b[2] for b in boxes)+2), min(SIZE,max(b[3] for b in boxes)+2))
        encoded = []
        for f in frames[i]:
            buffer = io.BytesIO()
            f.crop(box).save(buffer, format='PNG', optimize=True)
            encoded.append(base64.b64encode(buffer.getvalue()).decode())
        pet.update(loopMs=loops[i], width=box[2]-box[0], height=box[3]-box[1], frames=encoded)
        contact.alpha_composite(frames[i][FRAMES//4], (i % COLS * SIZE, i // COLS * SIZE))
    contact.convert('RGB').save(source / 'preview.png')
    write_modules(source, pets)
    print(f'Baked {len(pets)} pets; PNG frames require no browser at runtime.')


def write_modules(source, pets):
    # Claude's loader caps each source file at 1 MiB. Keep chunks below 700 KiB.
    destination = source / 'frames'
    destination.mkdir(exist_ok=True)
    groups, group, size = [], [], 0
    for pet in pets:
        data = json.dumps(pet, separators=(',', ':'))
        if group and size + len(data) > 700_000:
            groups.append(group)
            group, size = [], 0
        group.append(data)
        size += len(data)
    if group:
        groups.append(group)
    header = '// Generated by scripts/bake-pets.py. Artwork: MIT, see ../LICENSE.\n'
    for i, group in enumerate(groups):
        (destination / f'{i}.mjs').write_text(header + 'export const pets = [' + ','.join(group) + '];\n')
    (source / 'frames.mjs').write_text(
        '// Generated by scripts/bake-pets.py. Artwork: MIT, see LICENSE.\n' +
        ''.join(f'import {{ pets as group{i} }} from "./frames/{i}.mjs";\n' for i in range(len(groups))) +
        'export const pets = [' + ','.join(f'...group{i}' for i in range(len(groups))) + '];\n')


if __name__ == '__main__':
    main()
